services:
  redis:
    image: redis:7-alpine
    container_name: redis_broker
    networks:
      - shared_network
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s
    restart: unless-stopped
    command: redis-server --appendonly yes

networks:
  shared_network:
    driver: bridge
    name: shared_network

volumes:
  redis_data:
    driver: local
